### ISSUE TITLE
Mojolicious deprecates use of Mojolicious::Routes::Route::over

### ISSUE THREAD

**Issue by toddbruner** [maxmind/Mojolicious-Plugin-WithCSRFProtection#1]
When using this plugin with current version of mojolicious you will see the following warning:

`Mojolicious::Routes::Route::over` is DEPRECATED in favor of Mojolicious::Routes::Route::requires at /usr/local/share/perl/5.22.1/Mojolicious/Plugin/WithCSRFProtection.pm line 74.`

The fix is simple:  replace "over"  WithCSRFProtection.pm with "requires".

I'm trying to submit a PR

**Comment by toddbruner** [comment]
With the Mojolicioius now at 9.0, this is breaking completely.  Please See my Pull Request which will fix this.

**Comment by oschwald** [comment]
Sorry for the delay on review. We are no longer using this module ourselves. Would you be interested in taking over ownership of it? We could transfer the repo to you and provide you with comaint on PAUSE.

**Comment by toddbruner** [comment]
I've applied for a pause account.  I share it with you once I receive it.
Thanks,
Todd
------------------------------
todd.bruner@gmail.com

**Comment by oschwald** [comment]
Are you still interested in taking over this module? If not, we may go ahead an archive the repo.

**Comment by toddbruner** [comment]
Gregory:

Yes.  Sorry, I've been swamped.  I'll send you my PAUSE account once I
finalize it.

Todd
------------------------------
***@***.***

**Comment by toddbruner** [comment]
My PAUSE userId is "tbruner"
Let me know what other actions I need to take.
------------------------------
***@***.***

**Comment by oschwald** [comment]
Thanks. I made you the primary maintainer of the module in PAUSE.

**Comment by toddbruner** [comment]
Would you mind adding me, if possible to the github repo?  If that isn't
possible, I'll fork it.  My github account is ***@***.***
Thanks,
Todd
------------------------------
***@***.***

**Comment by oschwald** [comment]
I tried transferring it and got an error about a repository already existing with that name, i.e., https://github.com/toddbruner/Mojolicious-Plugin-WithCSRFProtection. It might work if you delete or rename that.

**Comment by toddbruner** [comment]
Sorry about that.  I've deleted my forked copy.
------------------------------
***@***.***

**Comment by oschwald** [comment]
I had to transfer it to myself first due to GitHub's rules about orgs, but you should have received a transfer request.

**Comment by charsbar** [comment]
Hi, @toddbruner , what is the current status of the transfer? If you are not interested in this anymore, I would like to take it over.

**Comment by oschwald** [comment]
It appears that I transferred PAUSE ownership to TBRUNER. I am happy to transfer the repo to whoever the PAUSE owner ends up being. It would be nice to transfer this to someone who will maintain it.

**Comment by oalders** [comment]
@oschwald could you transfer the repo over to @charsbar? I'm with him at the Perl Toolchain Summit right now. This particular issue would be helpful in getting PAUSE to run via Docker. As it stands, they're pinning Mojolicious to an earlier version to get around this.

**Comment by oschwald** [comment]
I canceled the transfer to @toddbruner and initiated a new transfer to @charsbar. I'll let you sort out the PAUSE permissions, although please let me know if I can help.

**Comment by Leont** [comment]
I think this hasn't been resolved yet?

**Comment by rjbs** [comment]
This still isn't resolved.  I encountered it today.

**Comment by oalders** [comment]
@toddbruner if you want to transfer maint to me (OALDERS), I can help move things along.

**Comment by charsbar** [comment]
Shipped 1.01. Thank you everyone for your patience.
